In [ ]:
# Lambda function ---> a lambda function can take any number of arguments but can
# only have one expression
# syntax:
#  Lambda argukments : expression

x = lambda a : a + 5
print("total value: ",x(5))

x = lambda a, b : a * b
print("Total product",x(5, 6))

x = lambda a, b, c : a+b-c
print("Total product",x(4, 5, 6))

total value:  10
Total product 30
Total product 3

In [ ]:
#  Filter function --> it returns an iterator where the items are filtered through
#  a function to test if the item is accepted or not
# # syntax:
# # filter(function, iterable)

ages =[5,12,17,18,34,67,50]
def myFunc(x):
  if (x<=18):
    return True
  else:
    return False

kids = list(filter(myFunc, ages))
print(kids)

[5, 12, 17, 18]

In [ ]:
# Map Function() ---> it executes a specified function for each item in iterable.
# the item is sent to the function as parameter

a = ["3", "45", "89"]

# method 1
for i in range(len(a)):
  a[i] = int(a[i])
print(a)

a = ["3", "45", "89"]
# method 2\
b = list(map(int ,a))
print(b)

[3, 45, 89]
[3, 45, 89]

# Questions

In [ ]:
# 1. Lambda Add & Multiply

# Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument,
#  also create a lambda function that multiplies argument x with argument y and prints the result.

# Sample Output:
# 25
# 48
x = lambda a : a+15

print(x(10))

x = lambda a, b : a*b
print(x(12, 4))

25
48

In [ ]:
# 2. Function Lambda Generator

# Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.

# Sample Output:
# Double the number of 15 = 30
# Triple the number of 15 = 45
# Quadruple the number of 15 = 60
# Quintuple the number 15 = 75

def func_result(x):
  return lambda a : a*x

result = func_result(2)
print("Double the number of 15 = ",result(15))

result = func_result(3)
print("Triple the number of 15 = ",result(15))

result = func_result(4)
print("Quadruple the number of 15 = ",result(15))

result = func_result(5)
print("Quintuple the number of 15 = ",result(15))

Double the number of 15 =  30
Triple the number of 15 =  45
Quadruple the number of 15 =  60
Quintuple the number of 15 =  75

In [ ]:
# Write a Python program to sort a list of tuples using Lambda.

# Original list of tuples:
# [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
# Sorting the List of Tuples:
# [('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

subject_score = [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]

print("Original list of tuples:")
print(subject_score)

subject_score.sort(key = lambda x: x[1])

print("\nSorting the List of Tuples:")
print(subject_score)

Original list of tuples:
[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]

Sorting the List of Tuples:
[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

In [ ]:
# Write a Python program to square and cube every number in a given list of integers using Lambda.

# Original list of integers:
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Square every number of the said list:
# [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
# Cube every number of the said list:
# [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
x = lambda i : i**2
b = list(map(x, a))

print("Square every number of the said list:\n",b)

y = lambda i : i**3
c = list(map(y, a))

print("Cube every number of the said list:\n",c)

Square every number of the said list:
 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Cube every number of the said list:
 [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [ ]:
# Write a Python program to find whether a given string starts with a given character using Lambda.
# return true if string starts with p else false
check_p = lambda x: True if x.startswith('P') else False

print(check_p("Python"))
print(check_p("Hello"))

True
False

In [ ]:
# FILTER FUNCTION QUESTIONS

In [ ]:
# 6. Even Number Filter

# Write a Python function that filters out even numbers from a list of integers using the filter function.
num = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

def even(n):
  if(n%2==0):
    return True
  else:
    return False

print(list(filter(even , num)))

[4, 16, 36, 64, 100]

In [2]:
# # . Uppercase Extractor

# # Write a Python program that uses the filter function to extract all uppercase letters from a list of mixed-case strings.

# mixed_case_strings = ["Hello", "w3resource", "Python", "Filter", "Learning"]
# # def trav(n)
# #   n.isupper()


# 7. Prime Number Excluder

# Write a Python program that filters out prime numbers from a list of integers using the filter function.

In [8]:
# 7. Student Grade Filter

# Write a Python program that creates a list of dictionaries containing student information (name, age, grade)
#  and uses the filter function to extract students with a grade greater than or equal to 95.

students = [
    {"name": "Sam", "age": 17, "grade": 97},
    {"name": "Dev", "age": 16, "grade": 92},
    {"name": "Satya", "age": 17, "grade": 90},
    {"name": "Arun", "age": 16, "grade": 94},
    {"name": "Denis", "age": 17, "grade": 100},
]
def high_grades(student):
  return student["grade"] >= 95

print(list(filter(high_grades, students)))

<filter object at 0x7913c7ff0b20>

In [9]:
# 8. City Population Filter

# Write a Python program that creates a list of tuples, each containing a city name and its population.
# Use the filter function to extract cities with a population greater than 2 million.

cities = [
    ("New York", 8500000),
    ("Los Angeles", 4000000),
    ("Chicago", 2700000),
    ("Houston", 2300000),
    ("Phoenix", 1600000),
    ("Philadelphia", 1500000),
    ("San Antonio", 1500000),
]
def populated_cities(city):
  return city[1] > 2000000

print(list(filter(populated_cities, cities)))

[('New York', 8500000), ('Los Angeles', 4000000), ('Chicago', 2700000), ('Houston', 2300000)]

In [10]:
# 9. Word Length Filter

# Write a Python program that creates a list of words and use the filter function to extract words that contain more than five letters.


words = ["Red", "Green", "Orange", "White", "Black", "Pink", "Yellow"]

def long_words(word):
  return len(word) > 5
print(list(filter(long_words, words)))

['Orange', 'Yellow']

In [11]:
# Map function questions

In [14]:
# 1. Triple Numbers Map

# Write a Python program to triple all numbers in a given list of integers. Use Python map.
num = [1, 2, 3, 4, 5, 6, 7]

print(list(map(lambda x: x*3 , num)))

[3, 6, 9, 12, 15, 18, 21]

In [15]:
# 2. Add Three Lists Map Lambda

# # Write a Python program to add three given lists using Python map and lambda.

num1 = [1, 2, 3]
num2 = [4, 5, 6]
num3 = [7, 8, 9]

print(list(map(lambda x, y, z : x + y + z, num1, num2, num3)))

[12, 15, 18]

In [17]:
# 3. List Addition and Difference Map

# Write a Python program to add two given lists and find the difference between them. Use the map() function.

nums1 = [6, 5, 3, 9]
nums2 = [0, 1, 7, 7]

def add_sub(x, y):
  return x + y, x - y

print(list(map(add_sub, nums1, nums2 )))

[(6, 6), (6, 4), (10, -4), (16, 2)]

In [19]:
# 4. Convert Numbers to Strings Map

# Write a Python program to convert a given list of integers and a tuple of integers into a list of strings.

nums_list = [1, 2, 3, 4]
nums_tuple = (0, 1, 2, 3)

print(list(map(str , nums_list)))
print(list(map(str , nums_tuple)))

['1', '2', '3', '4']
['0', '1', '2', '3']

In [20]:
# 5. Strings to Lists Map

# Write a Python program to convert a given list of strings into a list of lists using the map function.

colors = ["Red", "Green", "Black", "Orange"]

def strToList(strng):
  return list(map(list, strng))

print(strToList(colors))

[['R', 'e', 'd'], ['G', 'r', 'e', 'e', 'n'], ['B', 'l', 'a', 'c', 'k'], ['O', 'r', 'a', 'n', 'g', 'e']]